apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: titan-prod

resources:
  - ../../base

nameSuffix: -prod

patches:
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
    target:
      kind: Deployment
      name: titan-api
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 5
    target:
      kind: Deployment
      name: titan-worker
  - patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 3
      - op: replace
        path: /spec/maxReplicas
        value: 20
    target:
      kind: HorizontalPodAutoscaler
      name: titan-api-hpa
  - patch: |-
      - op: replace
        path: /spec/minReplicas
        value: 5
      - op: replace
        path: /spec/maxReplicas
        value: 50
    target:
      kind: HorizontalPodAutoscaler
      name: titan-worker-hpa
  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: 200m
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: 1000m
    target:
      kind: Deployment
      name: titan-api

configMapGenerator:
  - name: titan-config
    behavior: merge
    literals:
      - TITAN_LOGGING_LEVEL=info
      - TITAN_WORKER_CONCURRENCY=20
      - TITAN_REDIS_POOL_SIZE=25
